### ISSUE TITLE
fatal error: 'clang-c/Index.h' file not found

### ISSUE THREAD

**Issue by Kleak** [dart-lang/ffigen#117]
when i try to use ffigen with `pub run ffigen --config fficonfig.yaml`

i got this error :
```sh
/home/kleak/.pub-cache/hosted/pub.dartlang.org/ffigen-1.0.6/lib/src/clang_library/wrapper.c:5:10: fatal error: 'clang-c/Index.h' file not found
#include <clang-c/Index.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.

[SEVERE] : Unable to create dynamic library automatically.
[SEVERE] : If LLVM (9+) is installed, try running:
[SEVERE] :   pub run ffigen:setup -Ipath/to/llvm/include -Lpath/to/llvm/lib
```

i have already setup everything with 
```sh
pub run ffigen:setup -I/usr/lib/clang/11/include  -L/usr/lib/clang/11/lib
```

How can i fix this? I have clang 11 installed with llvm 11.

**Comment by Kleak** [comment]
fixed my problem.
the path used during the setup phase was not good.

**Comment by ganapathiraju** [comment]
I still face this issue in Mac Catalina OS.
LLVM 11 is pre installed with Xcode.

**Comment by mannprerak2** [comment]
Hi @ganapathiraju,
You will probably need to install llvm, use `brew install llvm`

If it still doesn't work, you need to run setup like this and provide the path to llvm include and lib directories.
```
pub run ffigen:setup -Ipath/to/llvm/include -Lpath/to/llvm/lib
```

**Comment by ganapathiraju** [comment]
Hello @mannprerak2 ,

I am suspicisous of running `brew install llvm` because llvm might conflict with the pre-installed LLVM from XCode.
Therefore I tried below command in windows system
`flutter pub run ffigen:setup -Id:'D:\Program Files\LLVM\include\' -Ld:'D:\Program Files\LLVM\lib\'`
Yet the issue persists. I have ensuredthat environment variable is set to `D:\Program Files\LLVM\bin`

**Comment by mannprerak2** [comment]
@ganapathiraju 
> llvm might conflict with the pre-installed LLVM

I can't advise about this, but I think `brew` will not add these to your path, so it shouldn't cause any issues, I use a MacBook as well and it has no issues.

On your Windows system, can you try it with this - 
```bash
flutter pub run ffigen:setup -ID:\Progra~1\LLVM\include -LD:\Progra~1\LLVM\lib
```

**Comment by ganapathiraju** [comment]
Thanks @mannprerak2 ,

I have installed LLVM in directory that void "spacing". 

With the following command `flutter pub run ffigen:setup -ID:\LLVM\include -LD:\LLVM\lib` shows below output. But generated_bindings.dart file is not created.

Building Dynamic Library for libclang wrapper...
   Creating library D:\Projects\prototype\flutter\native_add\.dart_tool\ffigen\_v_1_1_0_wrapped_clang.lib and object D:\Projects\prototype\flutter\native_add\.dart_tool\ffigen\_v_1_1_0_wrapped_clang.exp

Created dynamic library.

**Comment by mannprerak2** [comment]
The setup phase creates a dynamic library for ffigen to use in `.dart_tool/ffigen`. This needs to be done for every project once (and everytime you update ffigen version or delete `.dart_tool`)

Now that its done, you can now call `pub run ffigen` to generate the bindings.

**Comment by ganapathiraju** [comment]
`flutter pub run ffigen` is throwing below error. 
Running in Directory: 'D:\Projects\prototype\flutter\native_add'
[SEVERE] : Expected value of key 'name' to be a valid public class name.
[SEVERE] : Please fix configuration errors and re-run the tool.
pub finished with exit code 1

Here is the pubspec.yaml file
`name: native_add
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ffi: ^0.1.3

dev_dependencies:
  ffigen:
    path: '../ffigen'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to ffigen.
ffigen:
  output: 'generated_binding.dart'
  name: 'Native Binding'
  description: 'Holds binding to native_header.h'
  headers:
    entry-points:
      - 'header/native_header.h'`

**Comment by mannprerak2** [comment]
```
Expected value of key 'name' to be a valid public class name.
```

The `name` config option is the class name, it cannot contain spaces - try `NativeBinding`

**Comment by ganapathiraju** [comment]
Thanks again @mannprerak2.
Now I am able to progress.  Now I will start adding complexities to header file.
